
flib_version=1.0.0-SNAPSHOT

mod_id=antibonemeal
curse_id=320757
mod_version=1.0.2
mod_name=AntiBonemeal
mod_group_id=com.lothrazar.antibonemeal
mod_license=SeeGithub
mod_authors=Lothrazar
mod_description=mod
curse_slug=absent-by-design
