
mod_id=antibonemeal
curse_id=320757
mod_version=1.0.2
mod_name=AntiBonemeal
mod_group_id=com.lothrazar.antibonemeal
mod_license=SeeGithub
mod_authors=Lothrazar
mod_description=mod
curse_slug=anti-bonemeal
modrinth_id=anti-bonemeal

flib_version=0.2.8
flib_file=8482026
